version: '2.1'

services:
  lint:
    container_name: lint
    image: github/super-linter
    working_dir: /tmp/lint
    environment:
      HOME: "/tmp/lint"
      RUN_LOCAL: "true"
      VALIDATE_BASH: "true"
      VALIDATE_DOCKERFILE_HADOLINTL: "true"
      VALIDATE_DOCKERFILE: "true"
      VALIDATE_ENV: "true"
      VALIDATE_GITLEAKS: "true"
      VALIDATE_JSON: "true"
      VALIDATE_TERRAFORM_TERRASCAN: "true"
      VALIDATE_TERRAFORM_TFLINT: "true"
      VALIDATE_YAML: "true"
    volumes:
      - ./:/tmp/lint
