#!/usr/bin/env bash

if [ ! -f "$HOME/.chef/knife-mvf-$1.rb" ]; then
    echo "$1 is not a valid chef environment. Not changing."
fi

rm ~/.chef/knife.rb
ln -s "$HOME/.chef/knife-mvf-$1.rb" ~/.chef/knife.rb
ks
