#!/usr/bin/env ruby

if [ ! -f ~/.chef/knife-mvf-$1.rb ]; then
    echo "$1 is not a valid chef environment. Not changing."
    return
fi
rm ~/.chef/knife.rb
ln -s ~/.chef/knife-mvf-$1.rb ~/.chef/knife.rb
ks
