#!/bin/bash

SCRIPTPATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"

input=$(echo "" | dmenu -nb "#2F343F" -sb white -sf black -fn "Inconsolata Medium-24" -p "timer>  ")
time=$(echo "$input" | cut -d" " -f1)
message=$(echo "$input" | cut -d" " -f2)

"$SCRIPTPATH/pomo" "$time" "$message"
